
<style>@media (max-width: 990px) {footer .footer-wrapper {display: none;}}</style>

<div class="page-margin"> 
	<div class="row">
		<div class="col-md-8">
			<div class="fund_raise">
				<img src="<?php echo($wo['fund']['image']); ?>" class="fund_main_img">
				<h2 class="fund_title"><a href="<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($wo['fund']['hashed_id']) ?>" style="text-decoration: none;"><?php echo stripslashes($wo['fund']['title']); ?></a></h2>
				<div class="read-blog-info-user">
					<div class="postMeta--author-avatar">
						<a href="<?php echo $wo['fund']['user_data']['url']?>">
							<img src="<?php echo $wo['fund']['user_data']['avatar']?>" alt="User Image">
						</a>
					</div>
					<div class="postMeta--author-text">
						<a href="<?php echo $wo['fund']['user_data']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['fund']['user_data']['username']; ?>"><?php echo $wo['fund']['user_data']['name']; ?></a>
						<span class="middot">·</span>
						<time><?php echo date("d M Y",$wo['fund']['time']); ?></time>
					</div>
				</div>
				<hr class="fund_raise_hr">
				<div class="fund_raise_btns">
					<?php if ($wo['user']['id'] != $wo['fund']['user_id'] && $wo['fund']['amount'] > $wo['fund']['raised']) { ?>
						<button type="button" class="btn btn-main" data-toggle="modal" data-target="#dont_modal"><?php echo $wo['lang']['donate']; ?></button>
					<?php } ?>
					<div class="dropdown">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="shr_dropdwn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php echo $wo['lang']['share'];?></button>
						<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="shr_dropdwn">
							<li><a class="dropdown-item" href="https://www.facebook.com/sharer.php?u=<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" target="_blank"><?php echo $wo['lang']['facebook'];?></a></li>
							<li><a class="dropdown-item" href="http://twitter.com/intent/tweet?text=<?php echo $wo['fund']['title'] ?>&amp;url=<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" target="_blank"><?php echo $wo['lang']['twitter'];?></a></li>
							<li><a class="dropdown-item" href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" target="_blank"><?php echo $wo['lang']['linkedin'];?></a></li>
							<li><a class="dropdown-item" href="http://pinterest.com/pin/create/button/?url=<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" target="_blank"><?php echo $wo['lang']['pinterest'];?></a></li>
						</ul>
					</div>
				</div>
				<div class="fund_raise_bar">
					<p><?php echo $wo['config']['currency_symbol_array'][$wo['config']['currency']].$wo['fund']['raised']; ?>  <?php echo $wo['lang']['raised_of']; ?> <?php echo $wo['config']['currency_symbol_array'][$wo['config']['currency']].$wo['fund']['amount']; ?></p>
					<div class="progress">
						<div class="progress-bar" role="progressbar" style="width: <?php echo $wo['fund']['bar']; ?>%" aria-valuenow="<?php echo $wo['fund']['bar']; ?>" aria-valuemin="0" aria-valuemax="<?php echo($wo['fund']['amount']) ?>"></div>
					</div>
				</div>
			</div>
			
			<?php if ($wo['config']['user_ads'] == 1): ?>
				<div id="sidebar-sticky-funding">
					<?php 
					  $wo['sidebar-ad'] = Wo_GetAdsByType('funding');
					  if (!empty($wo['sidebar-ad'])) {
						echo Wo_LoadPage('ads/includes/funding-ad');
					  }
					?>
					<div class="clear"></div>
				</div>
			<?php endif; ?>
			
			<div class="fund_raise">
				<h4 class="fund_widget_title"><?php echo $wo['lang']['info'];?></h4>
				<?php echo stripslashes($wo['fund']['description']); ?>
			</div>
			
		</div>
		<div class="col-md-4">
			<?php echo Wo_LoadPage('show_fund/sidebar') ?>
		</div>
		<div class="clear"></div>
		<br>		
           <?php echo Wo_LoadPage('footer/content'); ?>
	</div>
	<!-- .row -->
</div>

<div class="modal fade" id="dont_modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['donate']; ?></h4>
			</div>
			<div class="modal-body">
				<h3 class="text-center fund_dnt_hd"><span><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><path fill="currentColor" d="M9.06,1.93C7.17,1.92 5.33,3.74 6.17,6H3A2,2 0 0,0 1,8V10A1,1 0 0,0 2,11H11V8H13V11H22A1,1 0 0,0 23,10V8A2,2 0 0,0 21,6H17.83C19,2.73 14.6,0.42 12.57,3.24L12,4L11.43,3.22C10.8,2.33 9.93,1.94 9.06,1.93M9,4C9.89,4 10.34,5.08 9.71,5.71C9.08,6.34 8,5.89 8,5A1,1 0 0,1 9,4M15,4C15.89,4 16.34,5.08 15.71,5.71C15.08,6.34 14,5.89 14,5A1,1 0 0,1 15,4M2,12V20A2,2 0 0,0 4,22H20A2,2 0 0,0 22,20V12H13V20H11V12H2Z"></path></svg></span><?php echo $wo['lang']['amount']; ?></h3>
				<div id="amount_fund_alert"></div>
				<div class="fund_input">
					<input type="number" name="amount" class="form-control" placeholder="0.00" id="fund_donate_amount" onkeyup="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
					<div id="place"></div>
				</div>
				<div class="fund_butns">
					<button class="bank_payment btn btn-main" onclick="Wo_GetPaymentLink(0,0,'fund','hide');"><?php echo $wo['lang']['donate']; ?></button>
					<input type="hidden" class="form-control" id="fund_donate_id" value="<?php echo $wo['fund']['id']; ?>">
				</div>
			</div>
		</div>
	</div>
</div>