<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="page-margin wow_content">
			<div class="page-margin wow_creads_minstp wow__minstp start_up step-three-active">
				<div class="line">
					<div class="line_sec"></div>
					<div class="dot one"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z" /></svg></div>
					<div class="dot two"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg></div>
					<div class="dot three"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M6,10V7H4V10H1V12H4V15H6V12H9V10M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12Z" /></svg></div>
				</div>
				<div class="steps">
					<div class="step step-one"><?php echo $wo['lang']['ad_media']; ?></div>
					<div class="step step-two"><?php echo $wo['lang']['info']; ?></div>
					<div class="step step-three"><?php echo $wo['lang']['follow']; ?></div>
				</div>
				
				<h2><?php echo $wo['lang']['follow_head'];?></h2>
				<h4><?php echo $wo['lang']['get_latest_activity'];?></h4>
			</div>
		
			<div class="add-photo wow_usr_steps">
				<div class="row wow_frnd_usr">
				<?php
					$user_id = array();
					foreach ($wo['users'] as $wo['result']) {
						$user_id[] = $wo['result']['user_id'];
						$wo['result']['no_btn'] = true;
						echo Wo_LoadPage('start_up/user-result');
					}
					echo '<input type="hidden" name="users" id="users-id" value="' . implode(',' , $user_id) . '">';
				?>
				</div>
				<div class="clear"></div>
			</div>
			<div class="continue-button wow_usr_steps_cont">
				<small class="skip-step" onclick="Wo_SkipStep('startup_follow');"><?php echo $wo['lang']['start_up_skip'];?></small>
				<button class="con-button btn btn-main btn-mat" onclick="Wo_SubmitFollow();"><?php $string = str_replace('{number}', count($wo['users']), $wo['lang']['follow_num']); echo $string;?> <svg viewBox="0 0 24 24"><path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" /></svg></button>
			</div>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>

<script type="text/javascript">
function Wo_SubmitFollow() {
	$('.con-button').attr('disabled', true);
  $('.con-button').text("<?php echo $wo['lang']['please_wait'];?>");
	var users = $('#users-id').val();
	$.post(Wo_Ajax_Requests_File() + '?f=follow_users', {user:users}, function (data) {
		if (data.status == 200) {
			window.location.href = '<?php echo Wo_SeoLink('index.php?link1=start-up');?>';
		}
	});
}
</script>