<div class="page-margin wow_content mt-0">
	<div class="wo_page_hdng pag_neg_padd pag_alone">
		<div class="wo_page_hdng_innr">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M7,5H21V7H7V5M7,13V11H21V13H7M4,4.5A1.5,1.5 0 0,1 5.5,6A1.5,1.5 0 0,1 4,7.5A1.5,1.5 0 0,1 2.5,6A1.5,1.5 0 0,1 4,4.5M4,10.5A1.5,1.5 0 0,1 5.5,12A1.5,1.5 0 0,1 4,13.5A1.5,1.5 0 0,1 2.5,12A1.5,1.5 0 0,1 4,10.5M7,19V17H21V19H7M4,16.5A1.5,1.5 0 0,1 5.5,18A1.5,1.5 0 0,1 4,19.5A1.5,1.5 0 0,1 2.5,18A1.5,1.5 0 0,1 4,16.5Z"></path></svg></span> <?php echo $wo['lang']['activities'];?>
		</div>
	</div>
</div>
			
<div class="list-group profile-lists">

    <div id="following-list" class="row" style="margin: 0;">
        <?php $activities = Wo_GetActivities(array('me' => true, 'limit' => 20));?>
        <ul class="activity-container no-padding-left-list">
            <li >
                <?php
                    if (count($activities) == 0) {
                        echo '<h2><div class="no-activities-profile text-center">' . $wo['lang']['no_activities'] . '</div><h2>';
                    } else {
                        foreach ($activities as $wo['activity']) {
                            echo Wo_LoadPage('sidebar/activities-list');
                        }
                    }
                    ?>
            </li>
            <li>
                <div class="no-activities center-text"></div>
            </li>
        </ul>
        
    </div>
    <div class="clear"></div>
</div>
<?php
        if (count($activities) > 19) {
         	?>
         	<div class="load-more">
    				<button class="btn btn-default text-center pointer" onclick="Wo_GetMoreActivities(<?php echo $wo['user_profile']['user_id'];?>);">
    				<i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_activities']; ?></button>
    			</div>
         	<?php
        } 
        ?>
<script>
function Wo_GetMoreActivities(user_id) {
      var activity_container = $('.activity-container');
      var after_activity_id = $('.activity-container .activity:last').attr('data-activity-id');
      $.post(Wo_Ajax_Requests_File() + '?f=activities&s=get_more_activities', {
        after_activity_id: after_activity_id,
        user_id: user_id
      }, function (data) {
        if(data.status == 200) {
          if(data.html.length == 0) {
            $('.load-more').hide();
          } else {
            $('.activity-container').append(data.html);
          }
          $(".activity-container").animate({
            scrollTop: $('.activity-container')[0].scrollHeight
          }, 100);
          Wo_progressIconLoader(activity_container);
        }
      });
    }
</script>